-- Question bank v1 — 30 original questions (10 easy, 12 medium, 8 hard).
-- correct_index is always 0 in seed data; option order is shuffled per participant at runtime.
insert into questions (bank_version, position, category, difficulty, prompt, options, correct_index) values
(1, 1,  'analogy',        'easy',   'Glove is to hand as sock is to ___.',
  '["Foot","Shoe","Leg","Toe"]', 0),
(1, 2,  'word_relation',  'easy',   'Which word means most nearly the same as ABUNDANT?',
  '["Plentiful","Rare","Heavy","Generous"]', 0),
(1, 3,  'word_relation',  'easy',   'Which word means the OPPOSITE of EXPAND?',
  '["Contract","Explode","Extend","Inflate"]', 0),
(1, 4,  'number_series',  'easy',   'What number comes next: 3, 6, 9, 12, ___?',
  '["15","14","16","18"]', 0),
(1, 5,  'arithmetic',     'easy',   'Pencils cost 25 cents each. How much do 4 pencils cost?',
  '["$1.00","75 cents","$1.25","$2.00"]', 0),
(1, 6,  'arithmetic',     'easy',   'A carton holds 12 eggs. How many eggs are in half a carton?',
  '["6","4","8","3"]', 0),
(1, 7,  'logic',          'easy',   'All dogs bark. Rex is a dog. What must be true?',
  '["Rex barks","Rex bites","Rex is loud","Some dogs are quiet"]', 0),
(1, 8,  'proverb',        'easy',   '"Don''t put all your eggs in one basket" advises you to ___.',
  '["spread your risk","handle eggs carefully","avoid baskets","buy fewer eggs"]', 0),
(1, 9,  'calendar',       'easy',   'Today is Wednesday. What day will it be in two days?',
  '["Friday","Thursday","Saturday","Monday"]', 0),
(1, 10, 'spatial',        'easy',   'Which shape has the most sides?',
  '["Hexagon","Triangle","Square","Pentagon"]', 0),
(1, 11, 'analogy',        'medium', 'Author is to novel as sculptor is to ___.',
  '["Statue","Chisel","Museum","Marble"]', 0),
(1, 12, 'word_relation',  'medium', 'Which word means the OPPOSITE of RECKLESS?',
  '["Cautious","Brave","Careless","Rapid"]', 0),
(1, 13, 'number_series',  'medium', 'What number comes next: 5, 6, 8, 11, 15, ___?',
  '["20","19","21","26"]', 0),
(1, 14, 'number_series',  'medium', 'What number comes next: 40, 34, 28, 22, ___?',
  '["16","18","14","12"]', 0),
(1, 15, 'arithmetic',     'medium', 'A $40 shirt is discounted 25%. What is the sale price?',
  '["$30","$10","$32","$35"]', 0),
(1, 16, 'arithmetic',     'medium', 'A train travels 120 miles in 2 hours. What is its average speed?',
  '["60 mph","55 mph","65 mph","240 mph"]', 0),
(1, 17, 'logic',          'medium', 'If it rains, practice is canceled. Practice was NOT canceled. What must be true?',
  '["It did not rain","It rained","Practice was indoors","It cannot be determined"]', 0),
(1, 18, 'proverb',        'medium', '"A stitch in time saves nine" means ___.',
  '["fixing a problem early prevents bigger trouble","sewing is a valuable skill","nine repairs are better than one","time heals all wounds"]', 0),
(1, 19, 'pattern',        'medium', 'What letter comes next: A, C, E, G, ___?',
  '["I","H","J","K"]', 0),
(1, 20, 'calendar',       'medium', 'March 1 falls on a Monday. What day of the week is March 15?',
  '["Monday","Tuesday","Sunday","Wednesday"]', 0),
(1, 21, 'disambiguation', 'medium', '"The coach told the player he was late." Who was late?',
  '["It cannot be determined","The coach","The player","Neither of them"]', 0),
(1, 22, 'disambiguation', 'medium', '"Flying planes can be dangerous." Why is this sentence ambiguous?',
  '["It has two possible meanings","It contains a spelling error","It is actually a question","It states an opinion only"]', 0),
(1, 23, 'analogy',        'hard',   'Drought is to rain as famine is to ___.',
  '["Food","Hunger","Crops","Water"]', 0),
(1, 24, 'word_relation',  'hard',   'Which word means the OPPOSITE of FRUGAL?',
  '["Wasteful","Thrifty","Careful","Poor"]', 0),
(1, 25, 'number_series',  'hard',   'What number comes next: 2, 3, 5, 9, 17, ___?',
  '["33","31","34","35"]', 0),
(1, 26, 'arithmetic',     'hard',   'A team scored 24, 30, and 21 points in three games. How many points must they score in game 4 to average exactly 27?',
  '["33","30","31","35"]', 0),
(1, 27, 'logic',          'hard',   'All Larks are Mubs. No Mubs are Tocks. What must be true?',
  '["No Larks are Tocks","Some Larks are Tocks","All Mubs are Larks","It cannot be determined"]', 0),
(1, 28, 'proverb',        'hard',   '"Still waters run deep" suggests that ___.',
  '["quiet people often have hidden depth","deep water is dangerous","silence means agreement","calm seas make poor sailors"]', 0),
(1, 29, 'spatial',        'hard',   'How many edges does a cube have?',
  '["12","6","8","24"]', 0),
(1, 30, 'calendar',       'hard',   'A meeting starts at 11:40 AM and lasts 95 minutes. When does it end?',
  '["1:15 PM","1:05 PM","1:25 PM","12:45 PM"]', 0);
